export const UPLOAD_FILES = 'UPLOAD_FILES';
export const UPDATE_TORRENT_SPEED = 'UPDATE_TORRENT_SPEED';
export const UPDATE_FILE_DETAILS = 'UPDATE_FILE_DETAILS';

export const DOWNLOAD_COMPLETED = 'DOWNLOAD_COMPLETED';
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';

export const ERROR = 'ERROR';
export const PROCESSING = 'PROCESSING';